# Generated by Django 5.2.1 on 2025-05-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_alter_agendamento_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='salas_imagens/'),
        ),
    ]
