# Generated by Django 5.2.1 on 2025-07-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_agendamentocancelado'),
    ]

    operations = [
    ]
